id: gcp_elt
namespace: company.team

variables:
  file_id: "{{ trigger.date | dateAdd(-1, 'MONTHS') | date('yyyyMM') }}"
  gcs_path: "gs://{{kv('GCP_BUCKET_NAME')}}/{{trigger.date | dateAdd(-1, 'MONTHS') | date('yyyy-MM')}}"
  table: "{{kv('GCP_DATASET')}}.ridedata_{{trigger.date | dateAdd(-1, 'MONTHS') | date('yyyy_MM')}}"

tasks:
  - id: get_zipfile
    type: io.kestra.plugin.core.http.Download
    uri: https://s3.amazonaws.com/tripdata/{{ render(vars.file_id) }}-citibike-tripdata.zip

  - id: unzip
    type: io.kestra.plugin.compress.ArchiveDecompress
    algorithm: ZIP
    from: "{{ outputs.get_zipfile.uri }}"

  - id: each
    type: io.kestra.plugin.core.flow.ForEach
    concurrencyLimit: 0
    values: "{{ outputs.unzip.files | values }}"
    tasks:
      - id: csv_to_parquet
        type: io.kestra.plugin.scripts.python.Script
        taskRunner:
          type: io.kestra.plugin.scripts.runner.docker.Docker
        dependencies:
          - pandas
          - pyarrow
        script: |
          import pandas as pd

          df = pd.read_csv("{{ taskrun.value }}", low_memory=False)
          df.to_parquet(f"{{ render(vars.file_id) }}_{{ taskrun.iteration }}.parquet", index=False)
        outputFiles:
          - "*.parquet"

      - id: gcs_upload
        type: io.kestra.plugin.gcp.gcs.Upload
        from: "{{ outputs.csv_to_parquet[taskrun.value].outputFiles[render(vars.file_id) ~ '_' ~ taskrun.iteration ~ '.parquet' ] }}"
        to: "{{ render(vars.gcs_path) }}/{{ render(vars.file_id) }}-{{ taskrun.iteration }}.parquet"

  - id: bq_ridedata_table_ext
    type: io.kestra.plugin.gcp.bigquery.Query
    sql: |
      CREATE OR REPLACE EXTERNAL TABLE `{{kv('GCP_PROJECT_ID')}}.{{render(vars.table)}}_ext`
      (
        ride_id STRING OPTIONS (description = 'Ride ID'),
        rideable_type STRING OPTIONS (description = 'Rideable type'),
        started_at TIMESTAMP OPTIONS (description = 'Started at'),
        ended_at TIMESTAMP OPTIONS (description = 'Ended at'),
        start_station_name STRING OPTIONS (description = 'Start station name'),
        start_station_id STRING OPTIONS (description = 'Start station ID'),
        end_station_name STRING OPTIONS (description = 'End station name'),
        end_station_id STRING OPTIONS (description = 'End station ID'),
        start_lat NUMERIC OPTIONS (description = 'Start longitude'),
        start_lng NUMERIC OPTIONS (description = 'Start latitude'),
        end_lat NUMERIC OPTIONS (description = 'End longitude'),
        end_lng NUMERIC OPTIONS (description = 'End latitude'),
        member_casual STRING OPTIONS (description = 'Member or casual ride')
      )
      OPTIONS (
        format = 'PARQUET',
        uris = ['{{ render(vars.gcs_path) }}/*.parquet']
      );

  - id: bq_yellow_table_tmp
    type: io.kestra.plugin.gcp.bigquery.Query
    sql: |
      CREATE OR REPLACE TABLE `{{kv('GCP_PROJECT_ID')}}.{{render(vars.table)}}_stg`
      AS
      SELECT
        "{{render(vars.file_id)}}" AS file_id,
        ride_id,
        started_at AS start_datetime,
        ended_at AS stop_datetime,
        start_station_id,
        start_station_name,
        start_lat AS start_station_latitude,
        start_lng AS start_station_longitude,
        end_station_id AS stop_station_id,
        end_station_name AS stop_station_name,
        end_lat AS stop_station_latitude,
        end_lng AS stop_station_longitude,
        rideable_type AS bike_type,
        member_casual AS user_type
      FROM `{{kv('GCP_PROJECT_ID')}}.{{render(vars.table)}}_ext`;

  - id: purge_files
    type: io.kestra.plugin.core.storage.PurgeCurrentExecutionFiles
    description: To avoid cluttering your storage, we will remove the downloaded files

pluginDefaults:
  - type: io.kestra.plugin.gcp
    values:
      serviceAccount: "{{kv('GCP_CREDS')}}"
      projectId: "{{kv('GCP_PROJECT_ID')}}"
      location: "{{kv('GCP_LOCATION')}}"
      bucket: "{{kv('GCP_BUCKET_NAME')}}"

triggers:
  - id: monthly_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 0 15 * *"
    