[project]
name = "nyc-citibike-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Bastien Winant", email = "armand.winant@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
nyc-citibike-pipeline = "nyc_citibike_pipeline:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
